services:
  - type: web
    name: charchahub-backend
    runtime: docker
    rootDir: backend
    plan: free
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SERVER_PORT
        value: 8080
